import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Optional: clean existing data
  await prisma.customerDetails.deleteMany();

  await prisma.customerDetails.createMany({
    data: [
      {
        globalAcctNo: "CUST001",
        customerName: "John Doe",
        customerAddress: "12 Palm Street, Lagos",
        region: "BENIN SOUTH",
        businessUnit: "SOKPONBA",
        serviceUnit: "UPPER SAKPONBA",
        customerType: "Residential",
        meterNumber: "MTR001",
        tariffClassId: 1, // assumes tariffClass with id 1 exists
        band: "A",
        feederId: 256, // assumes feeder with id 1 exists
        feederName11kv: "AGBARHA",
        feederName33kv: "Ikeja_33KV",
        source: "Grid",
        ticketNo: "TCK001",
        billStatus: "Paid",
        transformerName: "TX-101",
        amountBilled: 25000.5,
        totalOutstanding: 0,
      },
      {
        globalAcctNo: "CUST002",
        customerName: "Jane Smith",
        customerAddress: "20 Marina Road, Lagos",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Victoria Island",
        customerType: "Commercial",
        meterNumber: "MTR002",
        tariffClassId: 2,
        band: "B",
        feederId: 257,
        feederName11kv: "AGBARHO TOWN",
        feederName33kv: "Eko_33KV",
        source: "Grid",
        ticketNo: "TCK002",
        billStatus: "Unpaid",
        transformerName: "TX-205",
        amountBilled: 50000,
        totalOutstanding: 15000,
      },
      {
        globalAcctNo: "CUST003",
        customerName: "Michael Johnson",
        customerAddress: "45 Broad Street, Abuja",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Garki",
        customerType: "Industrial",
        meterNumber: "MTR003",
        tariffClassId: 3,
        band: "C",
        feederId: 337,
        feederName11kv: "EDO-TEX",
        feederName33kv: "Abuja_33KV",
        source: "Solar Hybrid",
        ticketNo: "TCK003",
        billStatus: "Pending",
        transformerName: "TX-307",
        amountBilled: 120000,
        totalOutstanding: 20000,
      },
      {
        globalAcctNo: "CUST004",
        customerName: "Grace Williams",
        customerAddress: "7 Airport Road, Kano",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Sabon Gari",
        customerType: "Residential",
        meterNumber: "MTR004",
        tariffClassId: 1,
        band: "D",
        feederId: 638,
        feederName11kv: "UPPER SAPELE",
        feederName33kv: "Kano_33KV",
        source: "Grid",
        ticketNo: "TCK004",
        billStatus: "Paid",
        transformerName: "TX-420",
        amountBilled: 18000.75,
        totalOutstanding: 0,
      },
      {
        globalAcctNo: "CUST005",
        customerName: "Samuel Brown",
        customerAddress: "9 Aba Road, Port Harcourt",
        region: "BENIN SOUTH",
        businessUnit: "EVBUOTUBU",
        serviceUnit: "Trans Amadi",
        customerType: "Commercial",
        meterNumber: "MTR005",
        tariffClassId: 2,
        band: "E",
        feederId: 639,
        feederName11kv: "UPPER SILUKO",
        feederName33kv: "PH_33KV",
        source: "Grid",
        ticketNo: "TCK005",
        billStatus: "Unpaid",
        transformerName: "TX-511",
        amountBilled: 40000,
        totalOutstanding: 10000,
      },
      {
        globalAcctNo: "CUST006",
        customerName: "Lucy Green",
        customerAddress: "15 Unity Street, Enugu",
        region: "BENIN SOUTH",
        businessUnit: "EVBUOTUBU",
        serviceUnit: "Independence Layout",
        customerType: "Residential",
        meterNumber: "MTR006",
        tariffClassId: 1,
        band: "B",
        feederId: 639,
        feederName11kv: "UPPER SILUKO",
        feederName33kv: "Enugu_33KV",
        source: "Grid",
        ticketNo: "TCK006",
        billStatus: "Pending",
        transformerName: "TX-612",
        amountBilled: 22000,
        totalOutstanding: 5000,
      },
      {
        globalAcctNo: "CUST007",
        customerName: "David Miller",
        customerAddress: "88 Sapele Road, Benin",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Uselu",
        customerType: "Industrial",
        meterNumber: "MTR007",
        tariffClassId: 7,
        band: "C",
        feederId: 638,
        feederName11kv: "UPPER SAPELE",
        feederName33kv: "Benin_33KV",
        source: "Gas",
        ticketNo: "TCK007",
        billStatus: "Paid",
        transformerName: "TX-713",
        amountBilled: 95000,
        totalOutstanding: 0,
      },
      {
        globalAcctNo: "CUST008",
        customerName: "Sarah Wilson",
        customerAddress: "33 Mission Road, Jos",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Rayfield",
        customerType: "Residential",
        meterNumber: "MTR008",
        tariffClassId: 1,
        band: "A",
        feederId: 638,
        feederName11kv: "UPPER SAPELE",
        feederName33kv: "Jos_33KV",
        source: "Grid",
        ticketNo: "TCK008",
        billStatus: "Unpaid",
        transformerName: "TX-814",
        amountBilled: 17000,
        totalOutstanding: 4000,
      },
      {
        globalAcctNo: "CUST009",
        customerName: "Peter Parker",
        customerAddress: "Spider Lane, Lagos",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Lekki",
        customerType: "Commercial",
        meterNumber: "MTR009",
        tariffClassId: 2,
        band: "B",
        feederId: 638,
        feederName11kv: "UPPER SAPELE",
        feederName33kv: "Lekki_33KV",
        source: "Grid",
        ticketNo: "TCK009",
        billStatus: "Pending",
        transformerName: "TX-915",
        amountBilled: 55000,
        totalOutstanding: 12000,
      },
      {
        globalAcctNo: "CUST010",
        customerName: "Bruce Wayne",
        customerAddress: "Wayne Manor, Gotham",
        region: "BENIN SOUTH",
        businessUnit: "ETETE",
        serviceUnit: "Maitama",
        customerType: "Industrial",
        meterNumber: "MTR010",
        tariffClassId: 3,
        band: "A",
        feederId: 638,
        feederName11kv: "UPPER SAPELE",
        feederName33kv: "Maitama_33KV",
        source: "Nuclear",
        ticketNo: "TCK010",
        billStatus: "Paid",
        transformerName: "TX-1010",
        amountBilled: 150000,
        totalOutstanding: 0,
      },
    ],
  });

  console.log("✅ Seeded 10 customers successfully");
}

main()
  .catch((e) => {
    console.error("❌ Seed error", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
